version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: SIAD
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SIAD
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
